//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SB.Tools.Classes.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Texts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Texts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SB.Tools.Classes.Language.Texts", typeof(Texts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aban.
        /// </summary>
        internal static string Aban {
            get {
                return ResourceManager.GetString("Aban", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adar.
        /// </summary>
        internal static string Adar {
            get {
                return ResourceManager.GetString("Adar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adar I.
        /// </summary>
        internal static string AdarI {
            get {
                return ResourceManager.GetString("AdarI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adar II.
        /// </summary>
        internal static string AdarII {
            get {
                return ResourceManager.GetString("AdarII", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to April.
        /// </summary>
        internal static string April {
            get {
                return ResourceManager.GetString("April", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to August.
        /// </summary>
        internal static string August {
            get {
                return ResourceManager.GetString("August", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Av.
        /// </summary>
        internal static string Av {
            get {
                return ResourceManager.GetString("Av", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azan Morning.
        /// </summary>
        internal static string AzanMorning {
            get {
                return ResourceManager.GetString("AzanMorning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azan Morocco.
        /// </summary>
        internal static string AzanMorocco {
            get {
                return ResourceManager.GetString("AzanMorocco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azan PM.
        /// </summary>
        internal static string AzanPM {
            get {
                return ResourceManager.GetString("AzanPM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azar.
        /// </summary>
        internal static string Azar {
            get {
                return ResourceManager.GetString("Azar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bahman.
        /// </summary>
        internal static string Bahman {
            get {
                return ResourceManager.GetString("Bahman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Christian.
        /// </summary>
        internal static string Christian {
            get {
                return ResourceManager.GetString("Christian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Christian Calendar.
        /// </summary>
        internal static string ChristianCalendarName {
            get {
                return ResourceManager.GetString("ChristianCalendarName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cow.
        /// </summary>
        internal static string Cow {
            get {
                return ResourceManager.GetString("Cow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to December.
        /// </summary>
        internal static string December {
            get {
                return ResourceManager.GetString("December", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dey.
        /// </summary>
        internal static string Dey {
            get {
                return ResourceManager.GetString("Dey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dhu al-Hijjah.
        /// </summary>
        internal static string Dhu_al_Hijjah {
            get {
                return ResourceManager.GetString("Dhu_al_Hijjah", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dhu al-Qi&apos;dah.
        /// </summary>
        internal static string Dhu_al_Qidah {
            get {
                return ResourceManager.GetString("Dhu_al_Qidah", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dog.
        /// </summary>
        internal static string Dog {
            get {
                return ResourceManager.GetString("Dog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elul.
        /// </summary>
        internal static string Elul {
            get {
                return ResourceManager.GetString("Elul", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurd when add {0} days to date {1}.
        /// </summary>
        internal static string ErrorInAddDays {
            get {
                return ResourceManager.GetString("ErrorInAddDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurd when add {0} hours to date {1}.
        /// </summary>
        internal static string ErrorInAddHours {
            get {
                return ResourceManager.GetString("ErrorInAddHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurd when add {0} mili seconds to date {1}.
        /// </summary>
        internal static string ErrorInAddMiliSeconds {
            get {
                return ResourceManager.GetString("ErrorInAddMiliSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurd when add {0} minutes to date {1}.
        /// </summary>
        internal static string ErrorInAddMinutes {
            get {
                return ResourceManager.GetString("ErrorInAddMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurd when add {0} months to date {1}.
        /// </summary>
        internal static string ErrorInAddMonths {
            get {
                return ResourceManager.GetString("ErrorInAddMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurd when add {0} seconds to date {1}.
        /// </summary>
        internal static string ErrorInAddSeconds {
            get {
                return ResourceManager.GetString("ErrorInAddSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurd when add {0} years to date {1}.
        /// </summary>
        internal static string ErrorInAddYear {
            get {
                return ResourceManager.GetString("ErrorInAddYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esfand.
        /// </summary>
        internal static string Esfand {
            get {
                return ResourceManager.GetString("Esfand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Farvardin.
        /// </summary>
        internal static string Farvardin {
            get {
                return ResourceManager.GetString("Farvardin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to February.
        /// </summary>
        internal static string February {
            get {
                return ResourceManager.GetString("February", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good Afternoon.
        /// </summary>
        internal static string GoodAfternoon {
            get {
                return ResourceManager.GetString("GoodAfternoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good Evening.
        /// </summary>
        internal static string GoodEvening {
            get {
                return ResourceManager.GetString("GoodEvening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good Morning.
        /// </summary>
        internal static string GoodMorning {
            get {
                return ResourceManager.GetString("GoodMorning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good Night.
        /// </summary>
        internal static string GoodNight {
            get {
                return ResourceManager.GetString("GoodNight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GoodTime.
        /// </summary>
        internal static string GoodTime {
            get {
                return ResourceManager.GetString("GoodTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hebrew.
        /// </summary>
        internal static string Hebrew {
            get {
                return ResourceManager.GetString("Hebrew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hebrew Calendar.
        /// </summary>
        internal static string HebrewCalendarName {
            get {
                return ResourceManager.GetString("HebrewCalendarName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hen.
        /// </summary>
        internal static string Hen {
            get {
                return ResourceManager.GetString("Hen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hijri.
        /// </summary>
        internal static string Hijri {
            get {
                return ResourceManager.GetString("Hijri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hijri Calendar.
        /// </summary>
        internal static string HijriCalendarName {
            get {
                return ResourceManager.GetString("HijriCalendarName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horse.
        /// </summary>
        internal static string Horse {
            get {
                return ResourceManager.GetString("Horse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iyyar.
        /// </summary>
        internal static string Iyyar {
            get {
                return ResourceManager.GetString("Iyyar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to January.
        /// </summary>
        internal static string January {
            get {
                return ResourceManager.GetString("January", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to July.
        /// </summary>
        internal static string July {
            get {
                return ResourceManager.GetString("July", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jumada al-awwal.
        /// </summary>
        internal static string Jumada_al_awwal {
            get {
                return ResourceManager.GetString("Jumada_al_awwal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jumada al-thani.
        /// </summary>
        internal static string Jumada_al_thani {
            get {
                return ResourceManager.GetString("Jumada_al_thani", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to June.
        /// </summary>
        internal static string June {
            get {
                return ResourceManager.GetString("June", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khordad.
        /// </summary>
        internal static string Khordad {
            get {
                return ResourceManager.GetString("Khordad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kislew.
        /// </summary>
        internal static string Kislew {
            get {
                return ResourceManager.GetString("Kislew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to March.
        /// </summary>
        internal static string March {
            get {
                return ResourceManager.GetString("March", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marheshwan.
        /// </summary>
        internal static string Marheshwan {
            get {
                return ResourceManager.GetString("Marheshwan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to May.
        /// </summary>
        internal static string May {
            get {
                return ResourceManager.GetString("May", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mehr.
        /// </summary>
        internal static string Mehr {
            get {
                return ResourceManager.GetString("Mehr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Midnight Prayer.
        /// </summary>
        internal static string MidnightPrayer {
            get {
                return ResourceManager.GetString("MidnightPrayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monkey.
        /// </summary>
        internal static string Monkey {
            get {
                return ResourceManager.GetString("Monkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month number {0} is not valid..
        /// </summary>
        internal static string MonthNumberIsNotValid {
            get {
                return ResourceManager.GetString("MonthNumberIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mordad.
        /// </summary>
        internal static string Mordad {
            get {
                return ResourceManager.GetString("Mordad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mouse.
        /// </summary>
        internal static string Mouse {
            get {
                return ResourceManager.GetString("Mouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muharram.
        /// </summary>
        internal static string Muharram {
            get {
                return ResourceManager.GetString("Muharram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friday.
        /// </summary>
        internal static string NameFriday {
            get {
                return ResourceManager.GetString("NameFriday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monday.
        /// </summary>
        internal static string NameMonday {
            get {
                return ResourceManager.GetString("NameMonday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturday.
        /// </summary>
        internal static string NameSaturday {
            get {
                return ResourceManager.GetString("NameSaturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunday.
        /// </summary>
        internal static string NameSunday {
            get {
                return ResourceManager.GetString("NameSunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thursday.
        /// </summary>
        internal static string NameThursday {
            get {
                return ResourceManager.GetString("NameThursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuesday.
        /// </summary>
        internal static string NameTuesday {
            get {
                return ResourceManager.GetString("NameTuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wednesday.
        /// </summary>
        internal static string NameWednesday {
            get {
                return ResourceManager.GetString("NameWednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nisan.
        /// </summary>
        internal static string Nisan {
            get {
                return ResourceManager.GetString("Nisan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date {0} not suported in date type {1} in .Net.
        /// </summary>
        internal static string NotSupportDate {
            get {
                return ResourceManager.GetString("NotSupportDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to November.
        /// </summary>
        internal static string November {
            get {
                return ResourceManager.GetString("November", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number {0} for month or {1} for year for hebrew is mistake..
        /// </summary>
        internal static string NumberMonthYearInHebrewIsMistake {
            get {
                return ResourceManager.GetString("NumberMonthYearInHebrewIsMistake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to October.
        /// </summary>
        internal static string October {
            get {
                return ResourceManager.GetString("October", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordibehesht.
        /// </summary>
        internal static string Ordibehesht {
            get {
                return ResourceManager.GetString("Ordibehesht", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Panther.
        /// </summary>
        internal static string Panther {
            get {
                return ResourceManager.GetString("Panther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persian Calendar.
        /// </summary>
        internal static string PersianCalendarName {
            get {
                return ResourceManager.GetString("PersianCalendarName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pig.
        /// </summary>
        internal static string Pig {
            get {
                return ResourceManager.GetString("Pig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rabbit.
        /// </summary>
        internal static string Rabbit {
            get {
                return ResourceManager.GetString("Rabbit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rabi al-awwal.
        /// </summary>
        internal static string Rabi_al_awwal {
            get {
                return ResourceManager.GetString("Rabi_al_awwal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rabi al-thani.
        /// </summary>
        internal static string Rabi_al_thani {
            get {
                return ResourceManager.GetString("Rabi_al_thani", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rajab.
        /// </summary>
        internal static string Rajab {
            get {
                return ResourceManager.GetString("Rajab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ramazan.
        /// </summary>
        internal static string Ramazan {
            get {
                return ResourceManager.GetString("Ramazan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Safar.
        /// </summary>
        internal static string Safar {
            get {
                return ResourceManager.GetString("Safar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to September.
        /// </summary>
        internal static string September {
            get {
                return ResourceManager.GetString("September", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sha&apos;aban.
        /// </summary>
        internal static string Shaaban {
            get {
                return ResourceManager.GetString("Shaaban", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shahrivar.
        /// </summary>
        internal static string Shahrivar {
            get {
                return ResourceManager.GetString("Shahrivar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shawwal.
        /// </summary>
        internal static string Shawwal {
            get {
                return ResourceManager.GetString("Shawwal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sheep.
        /// </summary>
        internal static string Sheep {
            get {
                return ResourceManager.GetString("Sheep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shevat.
        /// </summary>
        internal static string Shevat {
            get {
                return ResourceManager.GetString("Shevat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fr.
        /// </summary>
        internal static string ShortNameFriday {
            get {
                return ResourceManager.GetString("ShortNameFriday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mo.
        /// </summary>
        internal static string ShortNameMonday {
            get {
                return ResourceManager.GetString("ShortNameMonday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sa.
        /// </summary>
        internal static string ShortNameSaturday {
            get {
                return ResourceManager.GetString("ShortNameSaturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Su.
        /// </summary>
        internal static string ShortNameSunday {
            get {
                return ResourceManager.GetString("ShortNameSunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Th.
        /// </summary>
        internal static string ShortNameThursday {
            get {
                return ResourceManager.GetString("ShortNameThursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tu.
        /// </summary>
        internal static string ShortNameTuesday {
            get {
                return ResourceManager.GetString("ShortNameTuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We.
        /// </summary>
        internal static string ShortNameWednesday {
            get {
                return ResourceManager.GetString("ShortNameWednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siwan.
        /// </summary>
        internal static string Siwan {
            get {
                return ResourceManager.GetString("Siwan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snake.
        /// </summary>
        internal static string Snake {
            get {
                return ResourceManager.GetString("Snake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunrise.
        /// </summary>
        internal static string Sunrise {
            get {
                return ResourceManager.GetString("Sunrise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunset.
        /// </summary>
        internal static string Sunset {
            get {
                return ResourceManager.GetString("Sunset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tammuz.
        /// </summary>
        internal static string Tammuz {
            get {
                return ResourceManager.GetString("Tammuz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tebeth.
        /// </summary>
        internal static string Tebeth {
            get {
                return ResourceManager.GetString("Tebeth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tir.
        /// </summary>
        internal static string Tir {
            get {
                return ResourceManager.GetString("Tir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tishri.
        /// </summary>
        internal static string Tishri {
            get {
                return ResourceManager.GetString("Tishri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whale.
        /// </summary>
        internal static string Whale {
            get {
                return ResourceManager.GetString("Whale", resourceCulture);
            }
        }
    }
}
